version: "3.9"

networks:
  neo4j_user:

services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    expose:
      - 7474
      - 7687
    # env_file:
    #   - .env
    environment:
      - NEO4J_AUTH=neo4j/EchoesOfWisdom
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - ./neo4j_data:/data
    networks:
      - neo4j_user
    healthcheck:
        test: wget http://localhost:7474 || exit 1
        interval: 1s
        timeout: 10s
        retries: 20
        start_period: 3s

  data_loading:
    build:
      context: .
      dockerfile: data_loading/Dockerfile
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_HOST=neo4j
      - NEO4J_PORT=7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=EchoesOfWisdom
    networks:
      - neo4j_user

  rag:
    build:
      context: .
      dockerfile: rag/Dockerfile
    ports:
      - 8501:8501
    environment:
      - NEO4J_HOST=neo4j
      - NEO4J_PORT=7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=EchoesOfWisdom
    env_file:
      - .env
    networks:
      - neo4j_user
    depends_on:
      neo4j:
        condition: service_healthy
      data_loading:
        condition: service_completed_successfully

volumes:
  neo4j_data: