version: "3.9"
networks:
  neo4j_user:
services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474 # http://0.0.0.0:7474/
      - 7687:7687 # bolt
    expose:
      - 7474
      - 7687
    environment:
      - NEO4J_AUTH=neo4j/EchoesOfWisdom
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - ./neo4j_data:/data
    networks:
      - neo4j_user
    healthcheck:
        test: wget http://localhost:7474 || exit 1
        interval: 1s
        timeout: 10s
        retries: 20
        start_period: 3s
  data_insertion:
    build:
      context: .
      dockerfile: data_insertion.dockerfile
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_HOST=neo4j
      - NEO4J_PORT=7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=EchoesOfWisdom
    networks:
      - neo4j_user

volumes:
  neo4j_data: